### PR TITLE
第一次合併develop至main

### PR DESCRIPTION
**Pull request by Yun468**
#WeHelp 第二階段

姓名：吳佳芸 ( discord: Yun)

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
We should setup protection rule for `main` branch.

**Comment by Yun468** [comment]
姓名：吳佳芸 ( discord: Yun)

已修正 main  分⽀，新增保護規則

**Comment by cwpeng** [comment]
Try to re-request review from reviewers section in the right side of this page.

**Review by cwpeng — APPROVED** [review]
OK. Remember to merge pull request after review approval.

**Pull request merged**
