### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Yun468**
姓名：吳佳芸

http://35.76.166.101:3000/api/attractions?page=1
[http://35.76.166.101:3000/api/attractions?page=0&keyword=藝文館所]
[http://35.76.166.101:3000/api/attractions?page=0&keyword=北]
http://35.76.166.101:3000/api/attraction/10

備註：今天交作業之前才看到老師提醒的資料表設計問題，之後幾天會再修正，精簡code

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://35.76.166.101:3000/api/attraction/10 is incorrect.
2. `images` field contains image URLs with additional space character in the front.
3. We should use `LIMIT` to do range selection. You cannot depend on id to do it because id is only promised unique, not continuous number.

Solve issues and re-request review.

**Comment by Yun468** [comment]
i have a question on point3.
In my MySql table，i set a column which is "continuous number" for each material of our Json data name "ID". Column ID is not "_id" but a new new field. That is ,the column "ID" is not same to json data's "_id" in my MySql table. In my code, that is why i use "ID" but not "_id" on mysql searching language.
Is this be ok to the request?

**Comment by cwpeng** [comment]
I know, but still, ID is primary key, only PROMISE unique, not continuous number. Team members may delete data one day, so we lost some numbers between. It's acceptable operation based on primary key assumption.

**Comment by Yun468** [comment]
（補上pull request 訊息）

姓名：吳佳芸

http://35.76.166.101:3000/api/attractions?page=1
[http://35.76.166.101:3000/api/attractions?page=0&keyword=藝文館所]
[http://35.76.166.101:3000/api/attractions?page=0&keyword=北]
http://35.76.166.101:3000/api/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://35.76.166.101:3000/api/attraction/10 is still incorrect.
2. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"

**Comment by Yun468** [comment]
姓名：吳佳芸

http://35.76.166.101:3000/api/attractions?page=1
http://35.76.166.101:3000/api/attractions?page=0&keyword=藝文館所
http://35.76.166.101:3000/api/attractions?page=0&keyword=北
http://35.76.166.101:3000/api/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of http://35.76.166.101:3000/api/attraction/10 is still incorrect.

**Comment by Yun468** [comment]
抱歉讓老師看好多次，我看第一次的feedback時沒有弄懂原來老師在說地址的空格問題，現已修正，再麻煩

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of http://35.76.166.101:3000/api/attraction/10 is still incorrect.

Take attension on structure, hierarchy, column names carefully.

**Comment by Yun468** [comment]
想請問，我有注意到"_id" column name 的錯誤及data的value格式錯誤，想問的是"images field contains image URLs with additional space character in the front." 這個問題還存在嗎?

**Comment by cwpeng** [comment]
"images field contains image URLs with additional space character in the front." is fixed.

**Comment by Yun468** [comment]
如果還有錯的話，想請問是不是出在 column name 的排序，謝謝

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
